@startuml

namespace Barnabe {

    package Utilitaires #DDDDDD {
        class Rotation {
            - r : int
            + Rotation(int)
            + value() : int {const}
            + operator+(const Rotation&) : Rotation {const}
            + operator-(const Rotation&) : Rotation {const}
            + operator++() : Rotation&
            + operator++(int) : Rotation
            + operator==(const Rotation&) : bool {const}
            + operator!=(const Rotation&) : bool {const}

        }

        class Position {
            - posX : int
            - posY : int
            + Position(int, int)
            + x() : int {const}
            + y() : int {const}
            + operator+(const Position&) : Position {const}
            + operator+(const Rotation&) : Position {const}
            + operator-(const Position&) : Position {const}
            + operator==(const Position&) : bool {const}
            + operator!=(const Position&) : bool {const}
            + isNeighbour(const Position&) : bool {const}
            + class iterator
            + begin() : iterator {const}
            + end() : iterator {const}
            + cbegin() : iterator {const}
            + cend() : iterator {const}
            + toString() : string {const}

        }


        struct PositionHasher {
            operator()(const Position&) : size_t {const}
        }
    }



    package "Gestion Plateau" #ffeeee {
        class Cell {
            - id : int
            - color : Color
            - type : Type
            + Cell(int, Color, Type)
            + Cell(const Cell&)
            + ~Cell() {virtual}
            + getColor() : Color {const}
            + getEffectiveColor(const Rotation&) : Color {const} {virtual}
            + getType() : Color {const}
            + getID() : id {const}
            + displayTop(unsigned int) : string const {virtual}
            + displayBottom() : string {const} {virtual}
        }

        class BicolorCell {
           - secondaryColor : Color
           - rotation : Rotation
           + BicolorCell(int, Color, Type, Color, Rotation)
           + BicolorCell(const BicolorCell&)
           + getSecondaryColor() : Color {const}
           + getRotation() : Rotation {const}
           + setRotation(const Rotation&)
        }

        BicolorCell --> Cell
        abstract Tile {
           # {static} id : int
           # cells : vector<const Cell*>*
           + Tile()
           + ~Tile()
           + getSize() : unsigned int {const}
           + getCell(int) : const Cell* {const}
           + {abstract} calculatePositions(const Position&, Rotation&) : vector<Position>
           + class const_iterator
           + begin() : const_iterator {const}
           + end() : const_iterator {const}
           + cbegin() : const_iterator {const}
           + cend() : const_iterator {const}
        }

        class StartingTile {
            + StartingTile()
            + calculatePositions(const Position&, Rotation&) : vector<Position> {override}
        }
        class ClassicTile {
            + ClassicTile(Color, Type, Color, Type, Color, Type)
            + calculatePositions(const Position&, Rotation&) : vector<Position> {override}
        }
        class AthenaTile {
            - BicolorCell* cell;
            + AthenaTile(Color, Color, Type)
            + calculatePositions(const Position&, Rotation&) : vector<Position> {override}
        }

        StartingTile --> Tile
        ClassicTile --> Tile
        AthenaTile --> Tile

        Tile "1" *-- "1.." Cell


        together {
          class Board {
              {static} - stringToColor : map<string, Color>
              {static} - stringToType : map<string, Type>
              {static} - colorToString : map<Color, string>
              {static} - typeToString : map<Type, string>
              - cells : unordered_map<Position, pair<const Cell*, unsigned int>>
              - corner_tl : Position
              - corner_bl : Position
              + Board()
              + ~Board()
              + Board(const Board&)
              + operator=(const Board&) : Board&
              + getCell(const Position&) : const Cell* {const}
              + getCell(int, int) : const Cell* {const}
              + getHeight(const Position&) : unsigned int {const}
              + getHeight(int, int) : unsigned int {const}
              + setCell(const Position&, unsigned int, const Cell*)
              + setCell(int, int, unsigned int, const Cell*)
              + getCorners() : pair<Position, Position> {const}
              + class iterator
              + class const_iterator
              + begin() : iterator
              + end() : iterator
              + begin() : const_iterator {const}
              + end() : const_iterator {const}
              + cbegin() : const_iterator {const}
              + cend() : const_iterator {const}
              + toJsonBoard() : json {const}
              {static} + fromJsonBoard(const json&) : Board
          }

          Board "*" o-- "*" Cell

          class BoardManager {
              - board : Board*
              - startingTile : StartingTile*
              + BoardManager()
              + ~BoardManager()
              + BoardManager(const BoardManager&)
              + BoardManager(const Board& b)
              + operator=(const BoardManager&) : BoardManager&
              + getBoard() : const Board* {const}
              + setBoard(const BoardManager& bm)
              + place(const Tile*, Position, Rotation, bool) : int
          }

          BoardManager "1" *-- "1" Board
          BoardManager *-- "1" StartingTile
        }
    }


    enum Color {
        BLUE
        RED
        YELLOW
        GREEN
        PURPLE
    }

    enum Type {
        DISTRICT
        PLACE
        QUARRY
    }

    Color -- Cell
    Type -- Cell


    package QT #eeffee {
        abstract ContainerQt <typename T> {
            # size : int
            # cells : T
            + ContainerQt(QWidget*, int)
            + updateDisplay()
            # {abstract} draw()
            # {abstract} empty()
        }

        abstract CellQt {
            # size : int
            # w : int
            # h : int
            # pos : Position
            # locked : bool
            + CellQt(QWidget*, const Position&, bool, int)
            + paintEvent(QPaintEvent*) {override}
            {abstract} # brush() : QBrush {const}
            {abstract} # pen() : QPen {const}
            {abstract} # endPaintEventActions()
            + lock()
            + unlock()

        }

        class CellQtFull {
            {static} - colors : map<Color, pair<QColor, QColor>>
            {static} - colorText : map<Color, string>
            {static} - placeText : map<Color, string>
            - color : Color
            - type : Type
            - height : unsigned int
            - label : QLabel*
            + CellQtFull(Qwidget*, const Position&, bool, int, Color, Type, unsigned int)
            # brush() : QBrush {const} {override}
            # pen() : QPen {const} {override}
            # endPaintEventActions() {override}

        }

        Color -- CellQtFull
        Type -- CellQtFull

        CellQtFull --> CellQt

        class CellQtEmpty {
            + CellQtEmpty(QWidget*, const Position&, bool, int)
            # brush() : QBrush {const} {override}
            # pen() : QPen {const} {override}
            # endPaintEventActions() {override}
        }

        CellQtEmpty --> CellQt

        abstract TileQt {
            - tile : const Tile* t
            + TileQt(QWidget*, const Tile*, int)
            + empty() {override}
        }

        TileQt --> ContainerQt
        TileQt "*" o-- "1" Tile
        TileQt *-- "*" CellQt

        class ClassicTileQt {
            +ClassicTileQt(QWidget*, const ClassicTile*, int)
            +getTile() : const ClassicTile* {const}
            +setTile(const ClassicTile*)
            +draw() {override}
        }

        ClassicTileQt "*" o-- "1" ClassicTile


        class BoardQt {
            - board : const Board*
            + BoardQt(QWidget*, const Board*, int)
            + empty()  {override}
            + draw() {override}
            + getBoard() : const Board* {const}
            + setBoard(const Board*) {const}
            + lock()
            + unlock()
        }

        BoardQt --> ContainerQt
        BoardQt "*" o-- "1" Board
    }

}

namespace Amalena {
    class River{
        - tiles : vector<Tile*>
        - pile : Pile&
        - fillriver() : void
        + River(nb :size_t, pile : Pile&)
        + operator=(f : River&)
        +River (r : const River&)
        +~River()
        + giveTile(t : const Tile*)  : size_t {const}

    }
    River o-- "1..*" Tile
    class Pile{
        - tiles : vector<Tile*>
        - deck : Deck&
        + Pile (d: deck, t: vector<Tile*>)
        +~Pile()
        + isempty() : bool {const}
        + Draw() :Tile*

    }
    Pile o-- "1..*" Tile

}

namespace Eloise {
    class Player {
            - static stones_distribution : size_t
            - name : string
            - board : BoardManager
            - stones : int

            + Player(s : string)
            + ~Player()
            + getName() : const string&
            + getStones() : int
            + getBoard() : const BoardManager&
            + setBoard(b : BoardManager)
            + setStones(n : int)
            + addStones(n : int)
            + playTurn(t : Tile) <<virtual>>
        }

        Player *-- "1" BoardManager

        class Architect {
            - difficulty : int
            - architect_tiles : vector<Tile*>

            + Architect(name : string, d : int)
            + playTurn(t : Tile) <<override>>
        }

        Player <|-- Architect

    class Deck {
       + {static} stringToColor : map<string, Color>
       + {static} stringToType : map<string, Color>
       - tiles : vector<ClassicTile*>
       + Deck()
       + ~Deck()

    }

    class Game {
        - players : vector<Player*>
        - current_player : size_t
        - nb_players : size_t
        - static nb_players_max : size_t

        - deck : Eloise::Deck*
        - pile : Amalena::Pile*
        - river : Amalena::River*

        - Game(nb_players : size_t)
        - ~Game()

        - Game(Game) = delete
        - operator=(Game) = delete

        - static instance : Game*

        + static giveInstance(nb_players : size_t) : Game&
        + static freeInstance() : void
        + getNbPlayers() : const size_t&
        + static getNbPlayersMax() : const size_t&
        + getCurrentPlayer() : const size_t&
        + addPlayer(name : string) : void
        + getPlayer(position : size_t) : Player*
        + displayPlayers() : void
        + nextPlayer() : void
        + manageGame() : void
        + manageSoloGame(difficulty : int) : void
        + abandonGame() : void
        + pickRiver() : Tile&
        + endGame() : void
    }
}



Game *-- "1..*" Player
Game *-- "1" Deck
Game *-- "1" Pile
Game *-- "1" River

namespace Marilou {

    class ScoreVariants {
        + habitations : bool
        + marches : bool
        + casernes : bool
        + temples : bool
        + jardins : bool
    }

    abstract class Score {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScorePierre {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    abstract class ScoreCouleur {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreBleu {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreJaune {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreRouge {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreViolet {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreVert {
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    class ScoreGeneral {
        - couleurs : List<ScoreCouleur*>
        - scorePierre : ScorePierre
        + ScoreGeneral()
        + compute(player : Eloise::Player, variants : ScoreVariants) : int
    }

    Score <|-- ScorePierre
    Score <|-- ScoreCouleur
    Score <|-- ScoreGeneral

    ScoreCouleur <|-- ScoreBleu
    ScoreCouleur <|-- ScoreJaune
    ScoreCouleur <|-- ScoreRouge
    ScoreCouleur <|-- ScoreViolet
    ScoreCouleur <|-- ScoreVert

    ScoreGeneral o-- ScoreCouleur
    ScoreGeneral o-- ScorePierre
}

Marilou.Score ..> Eloise.Player

namespace Amaléna{



class  GameMemento{
- PlayersName :vector<string>
- PlayersStone :vector<int>
- boards :vector<map<pair<int,int>,pair<int, unsigned int>>>
- nbplayers : size_t
- currentplayer : size_t
- variante : string
- GameMemento(playersName :vector<string>,PlayersStone : vector<int> boards, nbplayers : size_t,
currentplayer : size_t, variante : string)
-~GameMemento()
- get_players_name() : vector<string>
- set_players_name(playersName : vector<string>) : void

- get_players_stone() : vector<int>
-set_players_stone(playersStone : vector<int>) : void

-get_boards() : vector<map<pair<int,int>, pair<int,unsigned int>>>
- set_boards(boards : vector<map<pair<int,int>, pair<int,unsigned int>>>) : void

-get_nbplayer() : size_t
-set_nbplayer(nbplayers : size_t) : void

- get_currentplayer() : size_t
-set_currentplayer(currentplayer : size_t) : void

-get_variante() : string
-set_variante(variante : string) : void
}


class SaveManager{
- gameMemento : GameMemento*
-fromjson(json data) : void
-tojson(): json
+ savemanager(GameMemento*)
+~SaveManager()
+ void save(filename : string)
+void restore (filename : string)
}


SaveManager o-- "1..*" GameMemento


}

@enduml